//Testing

@isTest
public class CreateAccountTest {
    static testMethod void testInsertAccount() {
        CreatingAccount ca = new CreatingAccount();
        ca.createAccount('TestclassAcc1');
    }
//A paragraph (from the Ancient Greek παράγραφος paragraphos, 
//"to write beside" or "written beside") is a self-contained unit of 
//a discourse in writing dealing with a particular point or idea. 
//A paragraph consists of one or more sentences.


//Adding new line 1

//Adding new line 2

}