public class MySampleApexClass {       //Class definition and body
   public static Integer myValue = 0;  //Class Member variable
   public static String myString = ''; //Class Member variable
   
   public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
   //adding line 1 to test commit validation
   //adding line 2 to test commit validation
   //adding line 3 to test commit validation
   //adding line 4 to test commit validation 
      myValue = myValue+10;
      return myValue;
   }
}